package main

import (
    "io"
    "os"
)

// Reads `error-template.html` file in the current directory
// and encodes it as string literal in `error-template.go`
func main() {
    out, _ := os.Create("error-template.go")
    out.Write([]byte("// generated by go run scripts/embed-template.go; DO NOT EDIT\n\n"))
    out.Write([]byte("package main\n\nconst (\n"))
    out.Write([]byte("errorTemplate = `"))
    f, _ := os.Open("error-template.html")
    io.Copy(out, f)
    out.Write([]byte("`\n"))
    out.Write([]byte(")\n"))
}
